package gogameloop

// TokenSource is the creator for the token (metrics or errors).
type TokenSource int

const (
	// TokenLoop is something generated by the game loop package directly.
	TokenLoop TokenSource = iota
	// TokenRender concerns Render().
	TokenRender TokenSource = iota
	// TokenSimulate concerns Simulate().
	TokenSimulate TokenSource = iota
)
